services:
  gg-quick-start:
    image: gg-quick-start
    build:
      context: ./build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/:/mnt/scripts/
      #- ../../:/gg/
      - ${GGQS_GG_HOME}:/gg/
    environment:
      - GGQS_AIO_SSH_CLONE_URL
    entrypoint: /mnt/scripts/entrypoint.sh
